Add template node files
esa-prl/ros2_best_practices pull request #1
Opened 2020-09-01 14:46 UTC by maxehrhardt

Also a file naming description was added to the ros2_best_practices_wiki

2020-09-07 15:33 UTC, wieset requested changes

2020-09-07 15:33 UTC, wieset commented on ros2_package_template/include/ros2_package_template/ros2_package_template_node.hpp
> +#define ROS2_PACKAGE_TEMPLATE_H
If we follow established practices, this should be named similar to the file name. Also, ROS2 developers are using a trailing underscore in their packages.

In addition, we should discuss if we maybe want to go for `#pragma once` include guards instead of `#ifndef`. We did that switch for Rock in the past.

```suggestion
#ifndef ROS2_PACKAGE_TEMPLATE_NODE_HPP_
#define ROS2_PACKAGE_TEMPLATE_NODE_HPP_
```

2020-09-07 15:33 UTC, wieset commented on ros2_package_template/include/ros2_package_template/ros2_package_template_node.hpp
> +#endif
VS code is not following POSIX standards and does not end files with newline character. GitHub complains about that (see red symbol at end of file in "Files changed" tab). I would suggest to change your settings accordingly: https://stackoverflow.com/questions/44704968/visual-studio-code-insert-new-line-at-the-end-of-files/44704969

2020-09-07 15:33 UTC, wieset commented on ros2_package_template/src/ros2_package_template_node.cpp
> +}
Same comment on newline at end of file

2020-09-07 15:42 UTC, wieset commented
- How about naming the node TemplateNode instead of Ros2PackageTemplateNode to make it shorter?
- Suggestion to add example lines to `CMakeLists.txt` to compile a template_node target
- Should we add example publish / subscribe code as well?
- Maybe also an example to use a parameter from `default.yaml`?

2020-09-09 13:54 UTC, maxehrhardt commented
We decided to not bloat the package template with example, since they can be found in the official ROS2 tutorials.

2020-09-09 14:49 UTC, mvoellmy commented
Looks generally good to me.

I guess it would be good to have the main function in the node file to fully follow our new convention.

I think adding the example lines to the CMakeLists as @wieset suggests makes sense.

Looks good to me otherwise! Same goes for the wiki entry!

2020-09-22 12:49 UTC, wieset approved these changes

2020-09-22 12:49 UTC, wieset commented
Looks good! There is still the leftover `ros2_package_template` folder with `ros2_package_template/include/ros2_package_template/ros2_package_template_node.hpp` that needs to be deleted. Afterwards we can merge.

2020-09-22 13:11 UTC, merged